version: '3.9'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nps
      MYSQL_ROOT_PASSWORD: toor
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    environment:
      XDEBUG_CONFIG: idekey=XDEBUG_PHPSTORM remote_host=172.17.0.1 remote_port=9001
      PHP_IDE_CONFIG: serverName=npp-nps.local
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    links:
      - mysql
    tty: true
  
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx

volumes:
  php-sock:
  mysql:
