app_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_translation:
    path:     /translation
    defaults:
        _controller: AppBundle:Default:translation

app_translation_multi:
    path:     /{_locale}/translation
    defaults:
        _controller: AppBundle:Default:translation
        _locale: ru
    requirements:
        _locale: en|ru|ua
