app:
    path:     /{_locale}/{path}
    defaults:
        _controller: AppBundle:Default:index
        path: ''
    requirements:
        _locale: en|ru|ua

app_default:
    path:     /{path}
    defaults: { _controller: AppBundle:Default:index, path: '' }

#app_index:
#    path:     /
#    defaults: { _controller: AppBundle:Default:index }

#app_index_multi:
#    path:     /{_locale}
#    defaults: { _controller: AppBundle:Default:index }
#    requirements:
#        _locale: en|ru|ua

app_locale:
    path:     /{_locale}
    defaults:
        _controller: AppBundle:Default:locale
    requirements:
        _locale: en|ru|ua
