app_index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_index_multi:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index }

app_translation:
    path:     /{_locale}/translation
    defaults:
        _controller: AppBundle:Default:translation
        _locale: ru
    requirements:
        _locale: en|ru|ua
