services:
    admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, 'AppBundle\Entity\Page', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: 'Page' }

    admin.products:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, 'AppBundle\Entity\Product', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: 'Products' }

    admin.inquiry:
        class: AppBundle\Admin\InquiryAdmin
        arguments: [~, 'AppBundle\Entity\Inquiry', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: 'Inquiries' }

    app.top_menu.voter.request:
        class: AppBundle\Menu\SmartUriVoter
        arguments:
            - "@service_container"
        tags:
            - { name: knp_menu.voter }
