services:
    admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, 'AppBundle\Entity\Page', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: 'Page' }

    admin.products:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, 'AppBundle\Entity\Product', ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: 'Products' }
